### PR TITLE
refactors group page

### LINKED ISSUE #681: refactor group management page
Looking at develop, I'm seeing all of the same issues that @13miciunasl is running into with #650 . Instead of trying to handle that and his changes, let's separate this into two distinct issues.

Test Lukas' code, then after merge I will go in and sort out the pre-existing issues.

screenshot_20160331-143009

### PR DESCRIPTION
**Pull request by lawhorkl**
closes uclibs/scholar_uc#681

finished up display issues on mobile for the manage groups page.

We need to test it on several devices and browsers.

Minimally on an iPhone and iPad, using chrome and firefox

As well as an android phone and tablet using chrome and firefox

I would do it, however I do not have access to these devices.

### CODE REVIEW

**Comment by lawhorkl** [comment]
dont merge until uclibs/scholar_uc#686 is solved

**Comment by lawhorkl** [comment]
After travis builds, everything's good :)

**Comment by lawhorkl** [comment]
ive eliminated the display bug to the best of my ability - further testing may reveal even more - should modify the test script to find any more issues like this

**Comment by jamesvanmil** [comment]
Seeing some form coloring issues in Scholar. You might need to port some of your CSS changes over there, too?

screen shot 2016-04-12 at 9 10 06 am

**Comment by lawhorkl** [comment]
I had to make a change in the app. Couldn't find anywhere else where the background color is affecting the application so I just removed it.

**Comment by jamesvanmil** [comment]
@lawhorkl can you squash this branch?

**Pull request merged**
