### PR TITLE
Increase size of thumbnail on collection show page

### LINKED ISSUE #737: Fix thumbnail display on collection show page
Remove generic thumbnail as default (show no thumbnail if not set by user).
Increase/normalize size of selected thumbnails.

### PR DESCRIPTION
**Pull request by lawhorkl**
closes uclibs/scholar_uc#737

### CODE REVIEW

**Comment by lawhorkl** [comment]
made two small changes to the collections spec to account for the new image size. if the image is still too small, we can change the datastream to `content` but that will fully disable any resizing.

edit: do not merge - found an issue with default thumbnail

**Comment by lawhorkl** [comment]
pushed up another change to this branch - default thumbnail display has been fixed. I've also taken the liberty of making it display quite a bit smaller - It does not need to be 50% of the page.

**Comment by haitzlm** [comment]
Can you make it a link?

**Comment by haitzlm** [comment]
Well - I tried...:-)

**Comment by lawhorkl** [comment]
Sorry? Tried what? Also, a link to where?

**Pull request merged**
