### PR TITLE
Enhancement/#741 file ownership

### PR DESCRIPTION
**Pull request by crowesn**
Resolves https://github.com/uclibs/scholar_uc/issues/741

### CODE REVIEW

**Comment by crowesn** [comment]
FYI @13miciunasl

**Comment by jamesvanmil** [comment]
Travis didn't start - closing and reopening

**Comment by 13miciunasl** [comment]
@crowesn and @jamesvanmil Is this safe to merge? I'm finally at the point where I need this!

**Comment by jamesvanmil** [comment]
@13miciunasl we think so, but would you review and manually test?

**Comment by 13miciunasl** [comment]
No problem

**Pull request merged**
