### PR TITLE
add selenium-webdriver

### PR DESCRIPTION
**Pull request by crowesn**
Resolves https://github.com/uclibs/scholar_uc/issues/773

Fixes broken feature tests associated with browse_everything.

### CODE REVIEW

**Comment by scherztc** [comment]
I am having a problem getting the test to pass in my local environment.  

Failure/Error: visit curation_concern_generic_work_path(work)
     Errno::ECONNREFUSED:
       Connection refused - connect(2) for "127.0.0.1" port 7055

I think it is a problem with my Firefox version (47).  See: https://github.com/jnicklas/capybara/issues/1709.

Maybe someone else could take a look at this too.  I am going to upgrade my Firefox and try again.

**Comment by hortongn** [comment]
Confirmed that this opens and crashes Firefox when I run this locally.  The issue Thomas links to above says to wait until an upgrade to Firefox 47 is released.  So let's hold on this for a bit longer.

**Comment by hortongn** [comment]
The Firefox issue is fixed and the tests are running properly now.  However, I'm getting two failing tests for clicking on the Browse Everything "Click here to upload remote files" button.  I confirmed by running the test app and trying to click the button myself.  In the test app, clicking on the button does nothing for me.  In the scholar_uc app, it works fine.

**Comment by hortongn** [comment]
I think the button problem described above is a Turbolinks gem version problem and should be fixed when PR https://github.com/uclibs/curate/pull/85 is merged.  So this branch can be rebased and tested again after that.

**Comment by scherztc** [comment]
@hortongn @crowesn   I am still having problems getting this to pass in my local environment.  I updated my Firefox to version 48.    Maybe feature test weren't meant to be ran individually.  Can you run it in our local environment? When we merge we will need to add Firefox to the list of dependencies in the README.  I am NOT going to include it in this Changelog for this deploy.

**Comment by crowesn** [comment]
Turns out my ff version was on 45 and tests were passing - after update to ff-48, tests are no longer passing. Digging deeper, this appears to be an issue with Firefox Driver, which is deprecated in versions >=ff-48. Selenium gem doesn't appear to have caught up with the issue yet:

> https://groups.google.com/d/msg/selenium-users/kDsWkujq0Y4/HoXsgMuhBwAJ

Backing down to ff-47 results in test passing.

So, this is ugly. Wondering if we can just confirm on another local machine, make a note and move on. Maybe add a note to display in the specs running capybara/selenium?

**Comment by crowesn** [comment]
Btw, I rebased this branch over develop this morning so everything should be up to date.

**Comment by hortongn** [comment]
I'm running these specs locally just to see what I get again.  I think the important thing is that Travis is passing.  We can deal with a flaky test or two in our local environments as long as Travis is happy.

**Pull request merged**
