### PR TITLE
block large files from being uploaded

### LINKED ISSUE #800: Research method for detecting files too big to upload through Hydra GUI in Fedora 3
Assume that our threshold for uploading files through Hydra and the web servers is 3 GB, in the Scholar 2.x stack environment.  Research a method for identifying and blocking these files whether coming from the workstation or Browse Everywhere.  

Possible help identified by @ntallman: 
http://stackoverflow.com/questions/1601455/how-to-check-file-input-size-with-jquery
http://stackoverflow.com/questions/7497404/get-file-size-before-uploading

### PR DESCRIPTION
**Pull request by lawhorkl**
closes uclibs/scholar_uc#800

Adds a validator for files that are greater than 3GB in size.

Note to reviewer: Refresh your page 2-3 times before testing as the browser doesn't detect new JS files without a full page reload.

### CODE REVIEW

**Comment by lawhorkl** [comment]
just rebased from develop to (hopefully) fix specs

**Comment by lawhorkl** [comment]
Accidentally closed the PR. Ignore please.

Should still be merged.

**Comment by hortongn** [comment]
Requesting advice from @newmanld and @ntallman here.  I've tested this PR and it does properly block files that are over 3GB in size.  Kyle did a great job.  The screenshot below shows what the user sees when they try a > 3GB file.  Do we want the alert to tell the user that they should email scholar@uc.edu for help with uploading their files(s)?  Should we also mention the limit in the existing help text to the right of the upload button?  That way the user will see what the limit is before they even try.

Let's figure out the exact text we want @lawhorkl to use.  My suggestions:
- Help text in right column: If any of your files are greater than 3 gigabytes or if you have trouble uploading your files, please email scholar@uc.edu to request alternative ways to add your content to Scholar@UC.
- Red alert box:: A file you selected is too large to upload to Scholar@UC via the website.  For files larger than 3 gigabytes, please email scholar@uc.edu to request alternative ways to add your content to Scholar@UC.

maxfile

**Comment by newmanld** [comment]
@hortongn – I think you are on the right track with both suggestions.  It might be better to direct people to our contact us form (https://scholar.uc.edu/contact_requests/new) instead of just giving a direct link to the email address.  In the future our methods may become more articulated and we may develop a separate form for this purpose.  So with this possible change, I think we could add both mechanisms you describe to this feature.

But before we merge this code into a deploy for production, these things may also need to be complete: a) we have added additional memory and swap space and are confident in supporting 3GB (issue #657) and b) we make similar progress with issue #799.  See comment about blocker in #799.

**Comment by hortongn** [comment]
Merging this PR depends on
1. Making the suggested changes in the comments above
2. Closing https://github.com/uclibs/scholar_uc/issues/748 and https://github.com/uclibs/scholar_uc/issues/799

**Comment by lawhorkl** [comment]
@hortongn made the content changes and resolved the merge conflct

**Pull request merged**
