### PR TITLE
filter params for script tag on collections

### PR DESCRIPTION
**Pull request by crowesn**

### CODE REVIEW

**Comment by crowesn** [comment]
Resolves https://github.com/uclibs/scholar_uc/issues/567

**Comment by jamesvanmil** [comment]
It's probably worthwhile to just drop this new helper in anywhere where `check_parameters?` already is.

**Comment by hortongn** [comment]
I'm going to run this branch against Hailstorm before merging.

**Comment by crowesn** [comment]
:+1:

**Comment by crowesn** [comment]
Force pushed a fix to ensure that we can pass hailstorm - I was comparing strings instead of regular expressions.

**Comment by hortongn** [comment]
@crowesn your branch does block searches that include <script> or javascript:alert, but it also prevents someone from creating a work that has those strings in them (title, description, etc.).  

The previous fix for javascript:alert only blocked people from searching on that string.  Works were allowed to contain the string.  I think that's how we still want this to work with <script> as well.  We may find out that Hailstorm now does require the fix to work the way you implemented it, but we probably want to start with only blocking searches and see.

**Comment by crowesn** [comment]
@hortongn Instead of a search query, this threat involves including malicious code in a param for a new collection. My code addresses this detected threat specifically and returns a 404, while retaining and expanding  the functionality to return 404 for blacklisted text in search queries. I had a discussion with Linda about this threat and we agreed that we should investigate form validation to prevent script tags from being submitted while displaying an error message in the form rather than returning 404. This would be my preference but I was going on instruction that we needed to return 404 in any case of detected malcontent.

```
Injected item: POST: collection[title]
Referer: https://scholar-qa.uc.edu/collections/new
```

[hailstorm source](https://hailstorm.uc.edu/Hailstorm.ARC/jobs/VulnerabilityListView.aspx?jrid=6d2d54b4-ea78-4868-8cde-b42ab36fa18f)

**Pull request merged**
