### PR TITLE
Add reader/reader groups feature

### PR DESCRIPTION
**Pull request by jamesvanmil**
I'd appreciate talking over this in the current sprint too, for a more thorough code review.

### CODE REVIEW

**Comment by jamesvanmil** [comment]
Depends on https://github.com/uclibs/scholar_uc/pull/598

**Comment by hortongn** [comment]
@jamesvanmil the help text for the read only groups says "Add groups to allow others to collaboratively **edit** this work."  Fix that and this is ready to merge.

**Comment by hortongn** [comment]
@jamesvanmil Actually, it looks like a couple of files in the app are overriding files in your branch of the gem:
- config/locales/sufia.en.yml
- app/views/curation_concern/base/_form_permission.html.erb

**Comment by jamesvanmil** [comment]
@hortongn taking a look...

**Comment by jamesvanmil** [comment]
@hortongn - Okay - I have:
- Fixed the reference to help info for reader groups (and squashed and pushed)
- Verified that the locales.yml is a non issue - this isn't an override, but an addition - there's a lot of other I18n text in there that isn't in the app version, which is displaying correctly
- Opened a PR to modify the _form_permissions partial with the same change I had made in the gem.

**Pull request merged**
