### PR TITLE
Feature/#649 send email on being added to works or groups

### LINKED ISSUE #649: Send email to any new delegates, editors or members of groups
As a submitter, I want to know if another submitter adds me as a delegate, an editor, or as a member of a group.  (Feedback from Scholar Camp 2016-03-02)

Done looks like: I receive an appropriately worded email whenever I have been added as a delegate, editor or member of a group, telling me the contact information of the person who assigned these rights to me, and the contact info for Scholar@UC if I have questions.

### PR DESCRIPTION
**Pull request by lawhorkl**
What a long, strange trip it's been.

To whomever has the good fortune of reviewing this baby, after the merge, please keep the branch open so that we may go back in and debug or change something if need be.

Should be reviewed with uclibs/scholar_uc#778
closes uclibs/scholar_uc#649

### CODE REVIEW

**Comment by lawhorkl** [comment]
@hortongn the branch has been squashed and everything is good to go.

**Comment by hortongn** [comment]
I'm going to deploy this branch to the dev server so I can fully test the email features.

**Comment by hortongn** [comment]
Something for all of us to note is that once this feature is merged in we will need to keep redis running in our development environments or the app will crash when we try to add people to groups, works, etc. 

We should probably come up with a documented procedure that will automatically start redis on our Macs so we never need to think about it.

**Comment by lawhorkl** [comment]
I noticed that - I know that in curate somehow it handles a down redis server gracefully with file permissions and thumbnails and things - it would be nice to somehow apply that to this.

**Comment by hortongn** [comment]
(making some notes here for myself)
- This and https://github.com/uclibs/scholar_uc/pull/778 should be reviewed and merged together
- The rake task `bundle exec rake resque:scheduler` needs to be run at the end of each deploy or emails will not send.
- The script that checks resque workers is seeing the resque scheduler task as a rogue worker.  Need to adjust the script for that.
- How can we make sure the resque scheduler or some other piece doesn't silently fail without us noticing?  
- What is needed on our local environments to keep the app from crashing?

**Comment by hortongn** [comment]
I've tested this pretty extensively on scholar-qa and haven't found any problems.  If anyone else wants to try it, log in as your self on QA and then also create a separate test user account.  Use the test user to add your personal account to groups, works, and delegates.  You should receive emails 15 minutes later.  I'll merge this at the end of Monday if I don't hear of any problems.

**Pull request merged**
