### PR TITLE
Add file request feature for files over 3 GB

### PR DESCRIPTION
**Pull request by 13miciunasl**

### CODE REVIEW

**Comment by jamesvanmil** [comment]
I think one more spec is vital - testing that the Mailer is receiving notify with the appropriate args.

Also - I think the request form should explain why you're unable to download it, e.g., with text like:

> "Scholar@UC is unable to support the download of files larger than 3GB. The Scholar@UC team will follow-up with you to arrange delivery of the file after you submit this form."

Also - the filesize threshold to trigger the appearance of request button should be in a configuration file - it's generally problematic to put business logic conditions (which are usually arbitrary and often used throughout an application) directly into MVC classes.

**Comment by 13miciunasl** [comment]
Not really sure where I should put the file size limit. None of the current config files seem appropriate

**Comment by jamesvanmil** [comment]
`config/initializers/curate_config.rb`?

**Comment by 13miciunasl** [comment]
@jamesvanmil Made the changes

**Comment by jamesvanmil** [comment]
The 3GB reference should be removed from the form too:

Try using: `helper.number_to_human_size(Curate.configuration.max_file_size, precision: 5
)`

**Comment by 13miciunasl** [comment]
Helper isn't defined in that class, and my attempts at requiring it have failed. Would it be too hack-y to just substring out the first integer in Curate.configuration.max_file_size?

**Comment by jamesvanmil** [comment]
That's in a view, so you should just be able to call `number_to_human_size` directly - I just included the `helper` because that's what I needed to do to run it from the rails console.

**Comment by 13miciunasl** [comment]
Oh okay, well its done then!

**Comment by jamesvanmil** [comment]
One more thing I think - since we're now adding to an initializer, we need a PR on the app to update the same config file, and to change the Gemfile reference to curate to the commit on this branch.

**Comment by 13miciunasl** [comment]
Wouldn't that leave the app pointing to an old branch once everything is merged?

**Comment by jamesvanmil** [comment]
The test that the mailer receives the appropriate arguments belongs in the controller test. We need to test that the create/post method is sending the correct message to the mailer.

https://relishapp.com/rspec/rspec-mocks/v/2-9/docs/message-expectations

**Comment by 13miciunasl** [comment]
Yeah I tried to do that all day yesterday, and settled with a mailer test as being better than nothing

**Comment by jamesvanmil** [comment]
This might be the better approach: https://www.relishapp.com/rspec/rspec-mocks/v/2-14/docs/message-expectations/expect-a-message-on-any-instance-of-a-class!

**Comment by 13miciunasl** [comment]
@jamesvanmil Is this what you had in mind?

**Comment by jamesvanmil** [comment]
Looks good - as soon as Travis is green we'll merge. Thanks!

**Pull request merged**
