### PR TITLE
auto populate college and dept in proxy submission

### PR DESCRIPTION
**Pull request by crowesn**
Resolves https://github.com/uclibs/scholar_uc/issues/823

### CODE REVIEW

**Comment by crowesn** [comment]
I need to change this to make sure it doesn't apply to student works and ETDs.

**Comment by jamesvanmil** [comment]
@crowesn is this ready for review now?

**Comment by crowesn** [comment]
Yes.

**Comment by jamesvanmil** [comment]
Code checks out, but this needs a spec demonstrating that it's not operating for Student Works or ETDs.

Ideally this would be implemented in such a way that we could test the functionality without having a test for each worktype, but as is I don't think it's worth refactoring, and a sample from each type would suffice.

**Comment by crowesn** [comment]
@jamesvanmil this should be ready to go.

**Pull request merged**
