### PR TITLE
Adds duration to a video's FITS characterization.

### PR DESCRIPTION
**Pull request by scherztc**
Fixes https://github.com/uclibs/scholar_uc/issues/592.

This code can be merged into develop, but to take advantage of the mapping, we will need to upgrade FITS on each environment to version 0.10.0

### CODE REVIEW

**Comment by 13miciunasl** [comment]
Not sure how to manually test this, but all the specs pass locally. +1

**Comment by jamesvanmil** [comment]
Okay I officially give up on merging this - FITS is still not co-operating and it's using a version I don't recall ever installing. There's not any chance that FITS is coming in automatically, is there?

**Comment by hortongn** [comment]
I've spent a good amount of time playing with this locally.  Here's what I found:

When Scholar tried to characterize videos, I was getting ffmpeg errors.  I was able to make it happy by reinstalling ffmpeg with certain options:
`brew reinstall ffmpeg --with-libvpx --with-libvorbis --with-fdk-aac`

After that I ffmpeg ran without errors.  I did find documentaiton suggesting that we should install ffmpeg with the following options to cover most video formats:
`brew install ffmpeg --with-fdk-aac --with-ffplay --with-freetype --with-libass --with-libquvi --with-libvorbis --with-libvpx --with-opus --with-x265`

I installed FITS 0.10.2 and it ran fine.  I verified it was using 0.10.2 by seeing the following in the characterization datastream:
`<fits xmlns="http://hul.harvard.edu/ois/xml/ns/fits/fits_output" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://hul.harvard.edu/ois/xml/ns/fits/fits_output http://hul.harvard.edu/ois/xml/xsd/fits/fits_output.xsd" version="0.10.2" timestamp="4/29/16 10:29 AM">`

When the characterization jobs finished, the only details I saw on the file page were like this:

```
            File format: avi (AVI, Audio/Video Interleaved Format)
            Mime type: video/avi
            File size: 1496576 
            Filename: bird.avi
            Original checksum: b7b5dae5300d9cbdc9f0b3b8497c3e39 
```

However, if I looked directly at the characterization datastream in Fedora I could see details like you see below.  So the details like duration, frame rate, and codec are there, but they are not being shown to the user on the file show page.  Details like `<duration>11833</duration>` indicate the video is 11.833 seconds long.  No thumbnail was generated for the videos.

```
        <metadata>
            <video>
                <location toolname="MediaInfo" toolversion="0.7.75" status="SINGLE_RESULT">
                    /private/var/folders/7m/k95bmyh92_5crtkglmqcmjrc0000gn/T/sufia:tt44pm97q-content.0.avi20160429-27395-mikw2g.avi
                </location>
                <mimeType toolname="MediaInfo" toolversion="0.7.75" status="SINGLE_RESULT">video/avi</mimeType>
                <format toolname="MediaInfo" toolversion="0.7.75" status="SINGLE_RESULT">AVI</format>
                <duration toolname="MediaInfo" toolversion="0.7.75" status="SINGLE_RESULT">11833</duration>
                <bitRate toolname="MediaInfo" toolversion="0.7.75" status="SINGLE_RESULT">1011798</bitRate>
                <dateModified toolname="MediaInfo" toolversion="0.7.75" status="SINGLE_RESULT">UTC 2016-04-29 14:29:43</dateModified>
                <track type="video" id="0" toolname="MediaInfo" toolversion="0.7.75" status="SINGLE_RESULT">
                    <videoDataEncoding>IV41</videoDataEncoding>
                    <codecId>IV41</codecId>
                    <codecCC>IV41</codecCC>
                    <codecName>IV41</codecName>
                    <codecInfo>Intel Indeo Video 4.1</codecInfo>
                    <compression>Unknown</compression>
                    <byteOrder>Unknown</byteOrder>
                    <bitDepth>8 bits</bitDepth>
                    <bitRate>1004605</bitRate>
                    <duration>11833</duration>
                    <trackSize>1485978</trackSize>
                    <width>256 pixels</width>
                    <height>240 pixels</height>
                    <frameRate>30.000</frameRate>
                    <frameCount>355</frameCount>
                    <aspectRatio>1.067</aspectRatio>
                </track>
            </video>
        </metadata>
```

**Comment by scherztc** [comment]
Were you able to test and mpg or mp4 file?

**Comment by scherztc** [comment]
Separated this into 2 distinct PRs.

**Pull request closed without merging**
