### PR TITLE
Displays email beside name in select lists when assigning rights

### PR DESCRIPTION
**Pull request by 13miciunasl**

### CODE REVIEW

**Comment by hortongn** [comment]
@13miciunasl Rebase this branch against develop to get James' rake fix and then Travis should be able to build properly.  See https://github.com/uclibs/scholar_uc/wiki/Quick-Reference#rebase-your-feature-branch-on-top-of-the-develop-branch

**Comment by hortongn** [comment]
I'm having two problems while testing this pull request:
1. I see the email address after the user's name when trying to add them as an editor to a work or to a group, but it's not working for adding delegates.
2. When I add someone to a group, their firstname + lastname + email is so long it bleeds past the width of the field.  I suspect we've never had someone with a long enough name that this was a problem, but now that we are adding on the email address I think we will see it frequently.  I'll attach a screenshot below.

new group curate

**Comment by 13miciunasl** [comment]
Still working on fixing the page in the screenshot, do NOT merge yet

**Comment by 13miciunasl** [comment]
Should be good to go once Travis passes!

**Comment by lawhorkl** [comment]
just thought of this, what we did with the width of the input is fixed. it may work better with a %-based width for smaller screens

**Comment by scherztc** [comment]
https://github.com/uclibs/scholar_uc/issues/650

**Comment by scherztc** [comment]
Looks good on group membership and editors, but not for delegates.  Since it looks great for these fields, I will merge this code and make new issue for delegates.

**Pull request merged**
