### PR TITLE
Add college and department facets

### PR DESCRIPTION
**Pull request by jamesvanmil**
This adds C&D fields to the form as flat metadata in the datastream, and adds a facet to the catalog index page.

This is a change in the metadata for ETDs and StudentWorks, which had used nested metadata - because of this we'll need to manually migrate these fields after deploy, with the repository manager login.

### CODE REVIEW

**Comment by jamesvanmil** [comment]
As this is another larger-than-average-PR - whoever reviews this is welcome to request a meeting to do a review in person and go over any questions about anything.

**Comment by hortongn** [comment]
This needs to be deployed and tested on scholar-dev before merge.  Waiting on Bamboo problem to be fixed to do that.

**Keep this issue open after this has been merged so we remember to do some data cleanup on production after deploy.**

**Comment by hortongn** [comment]
@jamesvanmil Your college and departments branch is now running on scholar-qa.  Should I wipe QA and start from scratch so you don't need to migrate old content?  Or can you test what you need with current content?  Just let me know.

**Comment by jamesvanmil** [comment]
Testing is going well - but I'm just not realizing that I didn't expand the list of Colleges beyond what was appropriate for Theses and Dissertations - going back to the OrgMaster chart to expand that list.

@hortongn no need to wipe QA - thanks!

**Comment by jamesvanmil** [comment]
@hortongn I made some fixes to better handle college names. Would you redeploy to QA from my (force) updated branch?

**Comment by hortongn** [comment]
@jamesvanmil When the app points to this branch of Curate, a couple of tests in the app fail.  See https://travis-ci.org/uclibs/scholar_uc/builds/149276196

**Comment by jamesvanmil** [comment]
Review with https://github.com/uclibs/scholar_uc/pull/842

**Comment by hortongn** [comment]
@jamesvanmil All tests passed.  I've re-deployed to QA.

**Comment by jamesvanmil** [comment]
I've finished reviewing on QA, and I'm satisfied that the following all works:
- Nested facet display
- Appropriate dropdowns of college and department for work types
- College and department fields auto selected for appropriate work types (everything but Student work and ETD), and fields are set correctly if the user changes the content and then edits the work
- College and department displaying as intended on work show page
- Fields are indexed and searchable

**Pull request merged**
